### ISSUE TITLE
main.py 실행 시 생기는 오류

### ISSUE THREAD

**Issue by joonavel** [100suping/sql-helper#8]
## 어떤 버그인가요?
main.py 실행 시 Table 'classicmodels.employees' doesn't exist"를 기반으로 한 오류 메시지가 뜹니다.

## 어떤 상황에서 발생한 버그인가요?
만들어낸 requirements.txt의 내용물을 설치한 다음
main.py 의 변경없이 python main.py를 실행 했을 때 다음과 같은 오류가 발생합니다.
![rag 오류](https://github.com/user-attachments/assets/d55164f4-8ebe-4438-a1f3-37543013162d)

## 예상 결과
예상했던 정상적인 결과는 agent.invoke()에 넣어준 "다이안의 이메일을 알려줘"에 대한 대답이 나오는 것이었습니다.
> 예상했던 정상적인 결과가 어떤 것이었는지 설명해주세요

## 참고할만한 자료(선택)
다음은 오류 전문입니다.
```
(t2l) joon@hojoon:/mnt/c/Users/joon/sesac/sql-helper$ python main.py
Traceback (most recent call last):
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'classicmodels.employees' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Users/joon/sesac/sql-helper/main.py", line 32, in <module>
    agent = cardinaliy(config)
            ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/joon/sesac/sql-helper/sql_rag.py", line 118, in cardinaliy
    artists = query_as_list(
              ^^^^^^^^^^^^^^
  File "/mnt/c/Users/joon/sesac/sql-helper/sql_rag.py", line 97, in query_as_list
    res = db.run(query)
          ^^^^^^^^^^^^^
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/langchain_community/utilities/sql_database.py", line 502, in run
    result = self._execute(
             ^^^^^^^^^^^^^^
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/langchain_community/utilities/sql_database.py", line 467, in _execute
    cursor = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/joon/.pyenv/versions/3.11.8/envs/t2l/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'classicmodels.employees' doesn't exist")
[SQL: SELECT DISTINCT lastName FROM employees]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

**Comment by pakyeon** [comment]
classicmodels DB에 employees 테이블이 없다고 나와있는데 DB 들어가서 테이블 확인해 봐야 어떤 문제인지 알 것 같습니다.

**Comment by pakyeon** [comment]
현재 문제 해결 확인했습니다.
확인하고 Close해주세요

**Comment by joonavel** [comment]
확인하였고 닫겠습니다
